"""empty message

Revision ID: 71972ae9a4ec
Revises: a1d2ea99eaa2
Create Date: 2022-04-17 23:10:54.537988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71972ae9a4ec'
down_revision = 'a1d2ea99eaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorite', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('weather', sa.Integer(), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('vehicle_class', sa.String(length=250), nullable=False),
    sa.Column('manufacturer', sa.String(length=250), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planets')
    op.drop_table('favorites')
    op.drop_table('vehicles')
    op.add_column('character', sa.Column('dob', sa.String(length=30), nullable=False))
    op.drop_column('character', 'height')
    op.drop_column('character', 'mass')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('character', 'dob')
    op.create_table('vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crew', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('passengers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('max_atmosphering_speed', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('consumables', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('cost_in_credits', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='vehicles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorite', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('planets',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rotation_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gravity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='planets_ibfk_1'),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('favorite')
    # ### end Alembic commands ###
